language: node_js
services: mongodb
notifications:
  email: false
  slack:
    secure: cGIjn10k+X70YpX89TSPQYYIUKzz/xseJ7nzUjH7VE478QGQKOzl31ZN+8EFSxWtaYxNH38/so5hgv3ulkYPWt/J3UcbhjxXN7a+xiASwku6/KtxnPT28EogDdkvN3smsLXJmjsUfKoJUH7bIVeFYESc7Qjznk9Fdv9iBmTC6xcxWFbaY7v6PqqPOTkkwchWYIFykxiiLlHeymw8vJTqpJIHuyhhpkKLpRiZw3X0EyDzagPLNQAJdeUogbxEaRxHt1geSIZAE5iVar+N+2utlA4Dj1UE8RodOBypLkDXHKl/DM61deBIy+6ZVbpMopbBdPE3QYxWV1Cp39aqJ0BFXPqm+iacLRqiJZKplHPGW1Y96AvcH9J9CmkY/6EYyoO9GgznMo1SZnvIDqEabo/L91qePiPsZYZAtF/Sj6JDRoJAqv59j3M+joQBKvjF8QebqosgnMXMGw5Kgi+H7x0aLxWND8cnBp8/lltET5Yqpm86+/j7NxieVPW20AXLOwzxi5K25CX2j3wuMjOwofVPJoKM7+Tulk+zTiaTKJuGZHXLdPoTLRHfPPc2n9peEo9BGX4+lkmCCyOnTofB537worDf+pNc+RpcZhTaMKsG+wOPw6Q4fBsk8NWxi6PcY5KRzB/Bc9E1QU2beZcPTxbaNqsi3ptdJmK/XXD650ixUGQ=
node_js: 6
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn run coverage
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: ikerin@gmail.com
  api_key:
    secure: MASOm3PQMDyYJVqfcdOF5YSybwDWu/SieyFp8699ZjvFjnh9Bmi4SRMiYrJUTKZSMmX/po1GwOa8zQX+xAy/e1jV+G+7a6T01qqUZwQjej7oqQ+u5ID2I6lpDwpHmVKc7snmdRFsol8YJ/aNkI0t65HxzTSFkc4tmPoYQuwQNtRq1UoyJMiGO9Q7r/AhOXM2LYut4DesT+0Pie8THpDrX7nOPMkD8i1gigt/G2vhjA9OljqZto0LOwJNjFJvqjqJOGSZbPR44nGuW1oJ/fz5nOhRoXaosu9aNdwk9iMEfc9UaA7aT0uYfHybvZAwNLSAuZVoIqt8BfYvMSKlMbTP8VMqJNhueX+u0Zfu1NuF9OgaZsA2sibQOAvV9F+3X1kJTIhmIv/uC3pW2nP9hS6aOnVTIRUp2Fc+zA3PjyaxdH06TJ36AV4zfI3SsDUsC3q1mAt+gEl7RIMEePOarakiQIIPRasAGKEa3+5RlP7lJwD73Za+y2zeyqFO1bPew55n0OE/C2FnGomFrYDBSrXocw92RI4oaMaQ0+j/tJStonjtGvK5XxQ6tle5YSX69TilPuyG5ks0AGuMtdK+/eJSLW+/R7xUGKYeofudR30Cy9NErexV9OUEwrOFW5iTwTQE2nSHVzW3u5HGUoJuqBknESA7pLFLaHBRCcHF/g3t1Nc=
  on:
    tags: true
    repo: enhancv/mongoose-subscriptions
